Now, using the same method, to webscrape Scrape the 2023 Fortune list of largest companies in Canada from wikipedia page

In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

accessing the url

In [7]:
web_url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_Canada'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

response = requests.get(web_url, headers=headers)
print('Status code\n', response.status_code)
print('\n--\n')
print('Content of the website\n', response.content[:2000])

Status code
 200

--

Content of the website
 b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of largest companies in Canada - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"532c611a-7176-4d3d-9294-9bf8913335fa","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":'

accessing different elements

In [8]:
soup_object = BeautifulSoup(response.content)

soup_object

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest companies in Canada - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"532c611a-7176-4d3d-9294-9bf8913335fa","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_Canada","wgTitle":"List of largest companies in Canada","wgCurRevisionId":1325259562,"wgRevisionId":1325259562,"wgArticleId":61383406,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of largest private companies by country","Lists of companies of Canada","Economy of Canada"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_Canada","wgRelevantArticleId":61383406,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q1371361","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.testKitchen","ext.wp25EasterEggs"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.46.0-wmf.19" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest companies in Canada - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="/w/index.php?title=List_of_largest_companies_in_Canada&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_Canada" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_Canada rootpage-List_of_largest_companies_in_Canada skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+Canada" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+Canada" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+Canada" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+Canada" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --><div class="wp25eastereggs-sitenotice"><div class="wp25eastereggs-sitenotice-landmark"></div></div></div>
</div>
<div class="vector-column-start">
<div class="vector-main-menu-container">
<div id="mw-navigation">
<nav aria-label="Site" class="vector-main-menu-landmark" id="mw-panel">
<div class="vector-pinned-container" id="vector-main-menu-pinned-container">
</div>
</nav>
</div>
</div>
<div class="vector-sticky-pinned-container">
<nav aria-label="Contents" class="mw-table-of-contents-container vector-toc-landmark" data-event-name="ui.sidebar-toc" id="mw-panel-toc">

trying to find and display the table

In [13]:
data_table = soup_object.find_all('table', 'wikitable sortable')[2]

data_table

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Fortune 500<br/>rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue<br/><small>(USD millions)</small>
</th>
<th>Profits<br/><small>(USD millions)</small>
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td>117
</td>
<td><a href="/wiki/Brookfield_Asset_Management" title="Brookfield Asset Management">Brookfield Asset Management</a>
</td>
<td><a href="/wiki/Finance" title="Finance">Finance</a>
</td>
<td style="text-align:center;">92,769
</td>
<td style="text-align:center;">2,056
</td>
<td style="text-align:center;">202,500
</td>
<td><a href="/wiki/Toronto" title="Toronto">Toronto</a>
</td></tr>
<tr>
<td>2
</td>
<td>214
</td>
<td><a href="/wiki/Alimentation_Couche-Tard" title="Alimentation Couche-Tard">Alimentation Couche-Tard</a>
</td>
<td><a href="/wiki/Retail" title="Retail">Retail</a>
</td>
<td style="text-align:center;">62,810
</td>
<td style="text-align:center;">2,683
</td>
<td style="text-align:center;">122,000
</td>
<td><a href="/wiki/Laval,_Quebec" title="Laval, Quebec">Laval</a>
</td></tr>
<tr>
<td>3
</td>
<td>270
</td>
<td><a href="/wiki/Royal_Bank_of_Canada" title="Royal Bank of Canada">Royal Bank of Canada</a>
</td>
<td><a class="mw-redirect" href="/wiki/Banking" title="Banking">Banking</a>
</td>
<td style="text-align:center;">52,062
</td>
<td style="text-align:center;">12,265
</td>
<td style="text-align:center;">91,427
</td>
<td>Montreal
</td></tr>
<tr>
<td>4
</td>
<td>277
</td>
<td><a href="/wiki/Cenovus_Energy" title="Cenovus Energy">Cenovus Energy</a>
</td>
<td><a class="mw-redirect" href="/wiki/Oil_and_Gas" title="Oil and Gas">Oil and Gas</a>
</td>
<td style="text-align:center;">51,406
</td>
<td style="text-align:center;">4,956
</td>
<td style="text-align:center;">5,998
</td>
<td><a href="/wiki/Calgary" title="Calgary">Calgary</a>
</td></tr>
<tr>
<td>5
</td>
<td>294
</td>
<td><a href="/wiki/Toronto-Dominion_Bank" title="Toronto-Dominion Bank">Toronto-Dominion Bank</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">48,700
</td>
<td style="text-align:center;">13,535
</td>
<td style="text-align:center;">94,945
</td>
<td>Toronto
</td></tr>
<tr>
<td>6
</td>
<td>327
</td>
<td><a href="/wiki/Suncor_Energy" title="Suncor Energy">Suncor Energy</a>
</td>
<td>Oil and Gas
</td>
<td style="text-align:center;">44,928
</td>
<td style="text-align:center;">6,975
</td>
<td style="text-align:center;">16,558
</td>
<td>Calgary
</td></tr>
<tr>
<td>7
</td>
<td>336
</td>
<td><a href="/wiki/George_Weston_Limited" title="George Weston Limited">George Weston Limited</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">43,838
</td>
<td style="text-align:center;">1,396
</td>
<td style="text-align:center;">221,285
</td>
<td>Toronto
</td></tr>
<tr>
<td>8
</td>
<td>365
</td>
<td><a href="/wiki/Enbridge" title="Enbridge">Enbridge</a>
</td>
<td>Oil and Gas
</td>
<td style="text-align:center;">40,964
</td>
<td style="text-align:center;">2,308
</td>
<td style="text-align:center;">12,050
</td>
<td>Calgary
</td></tr>
<tr>
<td>9
</td>
<td>392
</td>
<td><a href="/wiki/Nutrien" title="Nutrien">Nutrien</a>
</td>
<td><a href="/wiki/Agriculture" title="Agriculture">Agriculture</a>
</td>
<td style="text-align:center;">37,884
</td>
<td style="text-align:center;">7,660
</td>
<td style="text-align:center;">24,700
</td>
<td><a href="/wiki/Saskatoon" title="Saskatoon">Saskatoon</a>
</td></tr>
<tr>
<td>10
</td>
<td>394
</td>
<td><a href="/wiki/Magna_International" title="Magna International">Magna International</a>
</td>
<td><a class="mw-redirect" href="/wiki/Automotive_parts" title="Automotive parts">Automotive parts</a>
</td>
<td style="text-align:center;">37,840
</td>
<td style="text-align:center;">592
</td>
<td style="text-align:center;">158,000
</td>
<td><a href="/wiki/Aurora,_Ontario" title="Aurora, Ontario">Aurora</a>
</td></tr>
<tr>
<td>11
</td>
<td>399
</td>
<td><a href="/wiki/Power_Corporation_of_Canada" title="Power Corporation of Canada">Power Corporation of Canada</a>
</td>
<td>Finance
</td>
<td style="text-align:center;">37,419
</td>
<td style="text-align:center;">1,510
</td>
<td style="text-align:center;">37,300
</td>
<td><a href="/wiki/Montreal" title="Montreal">Montreal</a>
</td></tr>
<tr>
<td>12
</td>
<td>415
</td>
<td><a href="/wiki/Scotiabank" title="Scotiabank">Scotiabank</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">36,390
</td>
<td style="text-align:center;">7,701
</td>
<td style="text-align:center;">90,979
</td>
<td>Toronto
</td></tr>
<tr>
<td>13
</td>
<td>433
</td>
<td><a href="/wiki/Bank_of_Montreal" title="Bank of Montreal">Bank of Montreal</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">34,730
</td>
<td style="text-align:center;">10,513
</td>
<td style="text-align:center;">46,722
</td>
<td>Montreal
</td></tr>
<tr>
<td>14
</td>
<td>471
</td>
<td><a href="/wiki/Canadian_Natural_Resources" title="Canadian Natural Resources">Canadian Natural Resources</a>
</td>
<td>Oil and Gas
</td>
<td style="text-align:center;">32,503
</td>
<td style="text-align:center;">8,404
</td>
<td style="text-align:center;">10,035
</td>
<td>Calgary
</td></tr></tbody></table>

In [14]:
all_values = data_table.find_all('tr')
all_values[:3]

[<tr>
 <th>Rank
 </th>
 <th>Fortune 500<br/>rank
 </th>
 <th>Name
 </th>
 <th>Industry
 </th>
 <th>Revenue<br/><small>(USD millions)</small>
 </th>
 <th>Profits<br/><small>(USD millions)</small>
 </th>
 <th>Employees
 </th>
 <th>Headquarters
 </th></tr>,
 <tr>
 <td>1
 </td>
 <td>117
 </td>
 <td><a href="/wiki/Brookfield_Asset_Management" title="Brookfield Asset Management">Brookfield Asset Management</a>
 </td>
 <td><a href="/wiki/Finance" title="Finance">Finance</a>
 </td>
 <td style="text-align:center;">92,769
 </td>
 <td style="text-align:center;">2,056
 </td>
 <td style="text-align:center;">202,500
 </td>
 <td><a href="/wiki/Toronto" title="Toronto">Toronto</a>
 </td></tr>,
 <tr>
 <td>2
 </td>
 <td>214
 </td>
 <td><a href="/wiki/Alimentation_Couche-Tard" title="Alimentation Couche-Tard">Alimentation Couche-Tard</a>
 </td>
 <td><a href="/wiki/Retail" title="Retail">Retail</a>
 </td>
 <td style="text-align:center;">62,810
 </td>
 <td style="text-align:center;">2,683
 </td>
 <td style="text-align:center;">122,000
 </td>
 <td><a href="/wiki/Laval,_Quebec" title="Laval, Quebec">Laval</a>
 </td></tr>]

In [15]:
print(all_values[0])
print('--')
print(all_values[1])
print('--')
print(all_values[2])

<tr>
<th>Rank
</th>
<th>Fortune 500<br/>rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue<br/><small>(USD millions)</small>
</th>
<th>Profits<br/><small>(USD millions)</small>
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
--
<tr>
<td>1
</td>
<td>117
</td>
<td><a href="/wiki/Brookfield_Asset_Management" title="Brookfield Asset Management">Brookfield Asset Management</a>
</td>
<td><a href="/wiki/Finance" title="Finance">Finance</a>
</td>
<td style="text-align:center;">92,769
</td>
<td style="text-align:center;">2,056
</td>
<td style="text-align:center;">202,500
</td>
<td><a href="/wiki/Toronto" title="Toronto">Toronto</a>
</td></tr>
--
<tr>
<td>2
</td>
<td>214
</td>
<td><a href="/wiki/Alimentation_Couche-Tard" title="Alimentation Couche-Tard">Alimentation Couche-Tard</a>
</td>
<td><a href="/wiki/Retail" title="Retail">Retail</a>
</td>
<td style="text-align:center;">62,810
</td>
<td style="text-align:center;">2,683
</td>
<td style="text-align:center;">122,000
</td>
<td><a href="/wiki/Laval,_Quebec" title="Laval, Quebec">Laval</a>
</td></tr>

In [16]:
all_values[1].find_all('td')

[<td>1
 </td>,
 <td>117
 </td>,
 <td><a href="/wiki/Brookfield_Asset_Management" title="Brookfield Asset Management">Brookfield Asset Management</a>
 </td>,
 <td><a href="/wiki/Finance" title="Finance">Finance</a>
 </td>,
 <td style="text-align:center;">92,769
 </td>,
 <td style="text-align:center;">2,056
 </td>,
 <td style="text-align:center;">202,500
 </td>,
 <td><a href="/wiki/Toronto" title="Toronto">Toronto</a>
 </td>]

Saving as a table

In [21]:
import pandas as pd
fortune_500_2023_df = pd.DataFrame(columns = ['rank', 'Fortune_500_Rank', 'Name', 'Industry', 'Revenue_USD_millions', 'Profits_USD_millions', 'Employees', 'Headquarters']) # Create an empty dataframe
ix = 0 # Initialise index to zero

for row in all_values[1:]:
    values = row.find_all('td') # Extract all elements with tag <td>
    # Pick only the text part from the <td> tag
    rank = values[0].text
    Fortune_500_Rank = values[1].text
    Name = values[2].text
    Industry = values[3].text
    Revenue_USD_millions = values[4].text
    Profits_USD_millions = values[5].text
    Employees = values[6].text
    Headquarters = values[7].text

    
    fortune_500_2023_df.loc[ix] = [rank, Fortune_500_Rank, Name, Industry, Revenue_USD_millions, Profits_USD_millions, Employees, Headquarters] # Store it in the dataframe as a row
    ix += 1
    
# Print the first 5 rows of the dataframe
fortune_500_2023_df.head()

,rank,Fortune_500_Rank,Name,Industry,Revenue_USD_millions,Profits_USD_millions,Employees,Headquarters
0,1\n,117\n,Brookfield Asset Management\n,Finance\n,"92,769\n","2,056\n","202,500\n",Toronto\n
1,2\n,214\n,Alimentation Couche-Tard\n,Retail\n,"62,810\n","2,683\n","122,000\n",Laval\n
2,3\n,270\n,Royal Bank of Canada\n,Banking\n,"52,062\n","12,265\n","91,427\n",Montreal\n
3,4\n,277\n,Cenovus Energy\n,Oil and Gas\n,"51,406\n","4,956\n","5,998\n",Calgary\n
4,5\n,294\n,Toronto-Dominion Bank\n,Banking\n,"48,700\n","13,535\n","94,945\n",Toronto\n

getting rid of /n

In [23]:
import pandas as pd
top_companies_2023 = pd.DataFrame(columns = ['rank', 'Fortune_500_Rank', 'Name', 'Industry', 'Revenue_USD_millions', 'Profits_USD_millions', 'Employees', 'Headquarters']) # Create an empty dataframe
ix = 0 # Initialise index to zero

for row in all_values[1:]:
    values = row.find_all('td') # Extract all elements with tag <td>
    # Pick only the text part from the <td> tag
    rank = values[0].text.strip()
    Fortune_500_Rank = values[1].text.strip()
    Name = values[2].text.strip()
    Industry = values[3].text.strip()
    Revenue_USD_millions = values[4].text.strip()
    Profits_USD_millions = values[5].text.strip()
    Employees = values[6].text.strip()
    Headquarters = values[7].text.strip()

    
    top_companies_2023.loc[ix] = [rank, Fortune_500_Rank, Name, Industry, Revenue_USD_millions, Profits_USD_millions, Employees, Headquarters] # Store it in the dataframe as a row
    ix += 1
    
# Print the first 5 rows of the dataframe
top_companies_2023.head(10)

,rank,Fortune_500_Rank,Name,Industry,Revenue_USD_millions,Profits_USD_millions,Employees,Headquarters
0,1,117,Brookfield Asset Management,Finance,"92,769","2,056","202,500",Toronto
1,2,214,Alimentation Couche-Tard,Retail,"62,810","2,683","122,000",Laval
2,3,270,Royal Bank of Canada,Banking,"52,062","12,265","91,427",Montreal
3,4,277,Cenovus Energy,Oil and Gas,"51,406","4,956","5,998",Calgary
4,5,294,Toronto-Dominion Bank,Banking,"48,700","13,535","94,945",Toronto
5,6,327,Suncor Energy,Oil and Gas,"44,928","6,975","16,558",Calgary
6,7,336,George Weston Limited,Retail,"43,838","1,396","221,285",Toronto
7,8,365,Enbridge,Oil and Gas,"40,964","2,308","12,050",Calgary
8,9,392,Nutrien,Agriculture,"37,884","7,660","24,700",Saskatoon
9,10,394,Magna International,Automotive parts,"37,840",592,"158,000",Aurora

saving into csv file

In [24]:
top_companies_2023.to_csv('top_companies_2023.csv', index=False)

Question: Briefly explain (short bulletpoints) which parts of your code is different from the fortune 500 example.

Answer: 
- the link used was different 
- the table number was 2 instead of 0 
- the number of columns were more (3 compared to 7)